services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: highperf-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: highperf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: >
      postgres
        -c max_connections=500
        -c shared_buffers=1GB
        -c effective_cache_size=3GB
        -c work_mem=16MB
        -c maintenance_work_mem=512MB
        -c random_page_cost=1.1
        -c effective_io_concurrency=200
        -c checkpoint_completion_target=0.9
        -c wal_buffers=16MB
        -c default_statistics_target=100
        -c autovacuum=on
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
